# Generated by Django 5.0.6 on 2026-08-03 19:02

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(default='Hindi', max_length=40)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('content_rating', models.CharField(choices=[('ALL', 'All Ages'), ('13+', '13+'), ('16+', '16+'), ('18+', '18+')], default='ALL', max_length=10)),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='UPLOADING', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=20)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='videos/originals/%Y/%m/')),
                ('hls_manifest', models.CharField(blank=True, max_length=500)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='videos/posters/%Y/%m/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(default='thumbnail_and_metadata', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoTagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.tag')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'unique_together': {('video', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', through='videos.VideoTagMapping', to='videos.tag'),
        ),
        migrations.CreateModel(
            name='VideoThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='videos/thumbnails/%Y/%m/')),
                ('position_percent', models.PositiveSmallIntegerField(default=0)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='videos.video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.videothumbnail'),
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=10)),
                ('file', models.FileField(upload_to='videos/renditions/%Y/%m/')),
                ('bitrate_kbps', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='videos.video')),
            ],
            options={
                'unique_together': {('video', 'quality')},
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', 'visibility'], name='videos_vide_status_1398c6_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created_at'], name='videos_vide_created_1f1e45_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-view_count'], name='videos_vide_view_co_02bc14_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category'], name='videos_vide_categor_5f133b_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['slug'], name='videos_vide_slug_92e2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='videos_vide_search__29b818_gin'),
        ),
    ]
